cartpoleRLHF:
  policy_name: ppo
  learning_rate: 0.001
  n_steps: 32
  batch_size: 64
  n_epochs: 20
  gae_lambda: 0.8
  gamma: 0.98
  clip_range: 0.2
  ent_coef: 0.0
  vf_coef: 0.1
  num_envs: 8

cartpoleAIRL:
  policy_name: ppo
  learning_rate: 0.0005
  n_steps: 2048
  batch_size: 64
  n_epochs: 5
  gae_lambda: 0.95
  gamma: 0.95
  clip_range: 0.1
  ent_coef: 0.0
  vf_coef: 0.1
  num_envs: 8

pendulumRLHF:
  policy_name: ppo
  learning_rate: 0.001
  n_steps: 1024
  batch_size: 64
  n_epochs: 10
  gae_lambda: 0.95
  gamma: 0.9
  clip_range: 0.2
  ent_coef: 0.0
  vf_coef: 0.5
  num_envs: 4

pendulumAIRL:
  policy_name: ppo
  learning_rate: 0.001
  n_steps: 1024
  batch_size: 64
  n_epochs: 10
  gae_lambda: 0.95
  gamma: 0.9
  clip_range: 0.2
  ent_coef: 0.0
  vf_coef: 0.5
  num_envs: 4


